packages:
  - 'packages/*'
autoInstallPeers: true
strictPeerDependencies: false
nodeLinker: isolated
linkWorkspacePackages: true
resolvePeersFromWorkspaceRoot: true
overrides:
  react: 19.3.0
  react-dom: 19.3.0
allowBuilds:
  esbuild: false
  unrs-resolver: false
