import { TokenNames } from '../constant/TokenNames'
import type { IThemeSchema } from '../types'

export const darkenSchema: IThemeSchema = {
  [TokenNames.colorNote]: '#FDFDFE',
  [TokenNames.colorNoteActive]: '#FDFDFE',
  [TokenNames.colorNoteHover]: '#FDFDFE',
  [TokenNames.colorInfo]: '#FDFDFE',
  [TokenNames.colorInfoActive]: '#FDFDFE',
  [TokenNames.colorInfoHover]: '#FDFDFE',
  [TokenNames.colorSuccess]: '#FDFDFE',
  [TokenNames.colorSuccessActive]: '#FDFDFE',
  [TokenNames.colorSuccessHover]: '#FDFDFE',
  [TokenNames.colorWarning]: '#FDFDFE',
  [TokenNames.colorWarningActive]: '#FDFDFE',
  [TokenNames.colorWarningHover]: '#FDFDFE',
  [TokenNames.colorError]: '#FDFDFE',
  [TokenNames.colorErrorActive]: '#FDFDFE',
  [TokenNames.colorErrorHover]: '#FDFDFE',
  [TokenNames.colorBody]: '#4D4D4D',
  [TokenNames.colorBodyActive]: '#4D4D4D',
  [TokenNames.colorBodyHover]: '#4D4D4D',
  [TokenNames.colorCodeCaret]: '#AEAFAD',
  [TokenNames.colorCodeCaretActive]: '#AEAFAD',
  [TokenNames.colorCodeCaretHover]: '#AEAFAD',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorCodeTitleActive]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorCodeTitleHover]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorDelete]: '#ACB2B9',
  [TokenNames.colorDeleteActive]: '#ACB2B9',
  [TokenNames.colorDeleteHover]: '#ACB2B9',
  [TokenNames.colorHeading]: '#A6A6A6',
  [TokenNames.colorHeadingActive]: '#A6A6A6',
  [TokenNames.colorHeadingHover]: '#A6A6A6',
  [TokenNames.colorImageTitle]: '#808080',
  [TokenNames.colorImageTitleActive]: '#808080',
  [TokenNames.colorImageTitleHover]: '#808080',
  [TokenNames.colorInlineCode]: '#D81848',
  [TokenNames.colorInlineCodeActive]: '#D81848',
  [TokenNames.colorInlineCodeHover]: '#D81848',
  [TokenNames.colorLink]: '#4682B4',
  [TokenNames.colorLinkActive]: '#5C9FD6',
  [TokenNames.colorLinkHover]: '#5C9FD6',
  [TokenNames.colorLinkVisit]: '#4682B4',
  [TokenNames.colorMath]: '#BFBFBF',
  [TokenNames.colorMathActive]: '#BFBFBF',
  [TokenNames.colorMathHover]: '#BFBFBF',
  [TokenNames.colorBgNote]: '#474748',
  [TokenNames.colorBgNoteActive]: '#474748',
  [TokenNames.colorBgNoteHover]: '#474748',
  [TokenNames.colorBgInfo]: '#193C47',
  [TokenNames.colorBgInfoActive]: '#193C47',
  [TokenNames.colorBgInfoHover]: '#193C47',
  [TokenNames.colorBgSuccess]: '#003100',
  [TokenNames.colorBgSuccessActive]: '#003100',
  [TokenNames.colorBgSuccessHover]: '#003100',
  [TokenNames.colorBgWarning]: '#4D3800',
  [TokenNames.colorBgWarningActive]: '#4D3800',
  [TokenNames.colorBgWarningHover]: '#4D3800',
  [TokenNames.colorBgError]: '#4B1113',
  [TokenNames.colorBgErrorActive]: '#4B1113',
  [TokenNames.colorBgErrorHover]: '#4B1113',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: 'none',
  [TokenNames.colorBgBlockquoteActive]: 'none',
  [TokenNames.colorBgBlockquoteHover]: 'none',
  [TokenNames.colorBgCode]: '#1E1E1E',
  [TokenNames.colorBgCodeActive]: '#1E1E1E',
  [TokenNames.colorBgCodeHover]: '#1E1E1E',
  [TokenNames.colorBgCodeHighlight]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgCodeHighlightActive]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgCodeHighlightHover]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgInlineCode]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeActive]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeHover]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgTableHead]: '#28292A',
  [TokenNames.colorBgTableHeadActive]: '#28292A',
  [TokenNames.colorBgTableHeadHover]: '#28292A',
  [TokenNames.colorBgTableOddRow]: '#18191A',
  [TokenNames.colorBgTableOddRowActive]: '#18191A',
  [TokenNames.colorBgTableOddRowHover]: '#18191A',
  [TokenNames.colorBgTableEvenRow]: '#28292A',
  [TokenNames.colorBgTableEvenRowActive]: '#28292A',
  [TokenNames.colorBgTableEvenRowHover]: '#28292A',
  [TokenNames.colorBorderNote]: '#D4D5D8',
  [TokenNames.colorBorderNoteActive]: '#D4D5D8',
  [TokenNames.colorBorderNoteHover]: '#D4D5D8',
  [TokenNames.colorBorderInfo]: '#4CB3D4',
  [TokenNames.colorBorderInfoActive]: '#4CB3D4',
  [TokenNames.colorBorderInfoHover]: '#4CB3D4',
  [TokenNames.colorBorderSuccess]: '#009400',
  [TokenNames.colorBorderSuccessActive]: '#009400',
  [TokenNames.colorBorderSuccessHover]: '#009400',
  [TokenNames.colorBorderWarning]: '#E6A700',
  [TokenNames.colorBorderWarningActive]: '#E6A700',
  [TokenNames.colorBorderWarningHover]: '#E6A700',
  [TokenNames.colorBorderError]: '#E13238',
  [TokenNames.colorBorderErrorActive]: '#E13238',
  [TokenNames.colorBorderErrorHover]: '#E13238',
  [TokenNames.colorBorderBlockquote]: '#606770',
  [TokenNames.colorBorderBlockquoteActive]: '#606770',
  [TokenNames.colorBorderBlockquoteHover]: '#606770',
  [TokenNames.colorBorderCode]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLineno]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLinenoActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLinenoHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeading]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeadingActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeadingHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderImage]: '#7A6390',
  [TokenNames.colorBorderImageActive]: '#7A6390',
  [TokenNames.colorBorderImageHover]: '#7A6390',
  [TokenNames.colorBorderTable]: '#808080',
  [TokenNames.colorBorderTableActive]: '#808080',
  [TokenNames.colorBorderTableHover]: '#808080',
  [TokenNames.colorBorderThematicBreak]: '#e1e4e8',
  [TokenNames.colorBorderThematicBreakActive]: '#e1e4e8',
  [TokenNames.colorBorderThematicBreakHover]: '#e1e4e8',
  [TokenNames.fontFamilyCode]: `Consolas, 'Source Code Pro', 'Roboto Mono', monospace, sans-serif`,
  [TokenNames.fontFamilyHeading]: `'Comic Sans MS', 'lucida grande', 'lucida sans unicode', lucida, 'Hiragino Sans GB', 'Helvetica Neue', 'Microsoft Yahei', 'WenQuanYi Micro Hei', sans-serif`,
  [TokenNames.fontFamilyBody]: `'PingFang SC', system-ui, -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica, sans-serif`,
  [TokenNames.fontSizeCode]: '14px',
  [TokenNames.fontSizeBody]: '16px',
  [TokenNames.marginBlockNode]: '0 0 1.25em 0',
  [TokenNames.marginEmphasis]: '0 6px 0 2px',
  [TokenNames.marginThematicBreak]: '1.5em 0',
}
