import { TokenNames } from '@yozora/core-react-constant'

export const darkenSchema: Record<TokenNames, string> = {
  [TokenNames.colorNote]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorNoteActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorNoteHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfo]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfoActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfoHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccess]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccessActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccessHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarning]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarningActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarningHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorError]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorErrorActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorErrorHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorBody]: 'hsl(0deg, 0%, 30%)',
  [TokenNames.colorBodyActive]: 'hsl(0deg, 0%, 30%)',
  [TokenNames.colorBodyHover]: 'hsl(0deg, 0%, 30%)',
  [TokenNames.colorCodeCaret]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeCaretActive]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeCaretHover]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorCodeTitleActive]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorCodeTitleHover]: 'hsla(0deg, 0%, 90%, 0.8)',
  [TokenNames.colorDelete]: 'hsl(220deg, 5%, 68%)',
  [TokenNames.colorDeleteActive]: 'hsl(220deg, 5%, 68%)',
  [TokenNames.colorDeleteHover]: 'hsl(220deg, 5%, 68%)',
  [TokenNames.colorHeading]: 'hsl(0deg, 0%, 65%)',
  [TokenNames.colorHeadingActive]: 'hsl(0deg, 0%, 65%)',
  [TokenNames.colorHeadingHover]: 'hsl(0deg, 0%, 65%)',
  [TokenNames.colorImageTitle]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorImageTitleActive]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorImageTitleHover]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorInlineCode]: 'hsl(348deg, 70%, 52%)',
  [TokenNames.colorInlineCodeActive]: 'hsl(348deg, 70%, 52%)',
  [TokenNames.colorInlineCodeHover]: 'hsl(348deg, 70%, 52%)',
  [TokenNames.colorLink]: 'hsl(207deg, 53%, 50%)',
  [TokenNames.colorLinkActive]: 'hsl(207deg, 53%, 50%)',
  [TokenNames.colorLinkHover]: 'hsl(207deg, 53%, 50%)',
  [TokenNames.colorLinkVisited]: 'hsl(207deg, 53%, 50%)',
  [TokenNames.colorMath]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorMathActive]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorMathHover]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorBgNote]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgNoteActive]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgNoteHover]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgInfo]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgInfoActive]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgInfoHover]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgSuccess]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgSuccessActive]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgSuccessHover]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgWarning]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgWarningActive]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgWarningHover]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgError]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgErrorActive]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgErrorHover]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: 'none',
  [TokenNames.colorBgBlockquoteActive]: 'none',
  [TokenNames.colorBgBlockquoteHover]: 'none',
  [TokenNames.colorBgCode]: 'hsl(0deg, 0%, 12%)',
  [TokenNames.colorBgCodeActive]: 'hsl(0deg, 0%, 12%)',
  [TokenNames.colorBgCodeHover]: 'hsl(0deg, 0%, 12%)',
  [TokenNames.colorBgCodeHighlight]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgCodeHighlightActive]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgCodeHighlightHover]: 'hsla(210deg, 100%, 84%, 0.2)',
  [TokenNames.colorBgInlineCode]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeActive]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeHover]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgTableHead]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBgTableHeadActive]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBgTableHeadHover]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBgTableOddRow]: 'hsl(0deg, 0%, 9%)',
  [TokenNames.colorBgTableOddRowActive]: 'hsl(0deg, 0%, 9%)',
  [TokenNames.colorBgTableOddRowHover]: 'hsl(0deg, 0%, 9%)',
  [TokenNames.colorBgTableEvenRow]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBgTableEvenRowActive]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBgTableEvenRowHover]: 'hsl(200deg, 10%, 16%)',
  [TokenNames.colorBorderNote]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderNoteActive]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderNoteHover]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderInfo]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderInfoActive]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderInfoHover]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderSuccess]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderSuccessActive]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderSuccessHover]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderWarning]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderWarningActive]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderWarningHover]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderError]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderErrorActive]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderErrorHover]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderBlockquote]: 'hsl(207deg, 7%, 45%)',
  [TokenNames.colorBorderBlockquoteActive]: 'hsl(207deg, 7%, 45%)',
  [TokenNames.colorBorderBlockquoteHover]: 'hsl(207deg, 7%, 45%)',
  [TokenNames.colorBorderCode]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLineno]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLinenoActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderCodeLinenoHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeading]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeadingActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderHeadingHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorBorderImage]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderImageActive]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderImageHover]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderTable]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorBorderTableActive]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorBorderTableHover]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorBorderThematicBreak]: 'hsl(0deg, 0%, 88%)',
  [TokenNames.colorBorderThematicBreakActive]: 'hsl(0deg, 0%, 88%)',
  [TokenNames.colorBorderThematicBreakHover]: 'hsl(0deg, 0%, 88%)',
}
