import { TokenNames } from '../constant/token'

export const lightSchema: Record<TokenNames, string> = {
  [TokenNames.colorNote]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorNoteActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorNoteHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfo]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfoActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfoHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccess]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccessActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccessHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarning]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarningActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarningHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorError]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorErrorActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorErrorHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorBody]: 'hsl(0deg, 0%, 60%)',
  [TokenNames.colorBodyActive]: 'hsl(0deg, 0%, 60%)',
  [TokenNames.colorBodyHover]: 'hsl(0deg, 0%, 60%)',
  [TokenNames.colorCodeCaret]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeCaretActive]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeCaretHover]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorCodeTitleActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorCodeTitleHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorDelete]: 'hsl(210deg, 8%, 65%)',
  [TokenNames.colorDeleteActive]: 'hsl(210deg, 8%, 65%)',
  [TokenNames.colorDeleteHover]: 'hsl(210deg, 8%, 65%)',
  [TokenNames.colorHeading]: 'hsl(0deg, 0%, 25%)',
  [TokenNames.colorHeadingActive]: 'hsl(0deg, 0%, 25%)',
  [TokenNames.colorHeadingHover]: 'hsl(0deg, 0%, 25%)',
  [TokenNames.colorImageTitle]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorImageTitleActive]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorImageTitleHover]: 'hsl(0deg, 0%, 50%)',
  [TokenNames.colorInlineCode]: 'hsl(348deg, 60%, 47%)',
  [TokenNames.colorInlineCodeActive]: 'hsl(348deg, 60%, 47%)',
  [TokenNames.colorInlineCodeHover]: 'hsl(348deg, 60%, 47%)',
  [TokenNames.colorLink]: 'hsl(206deg, 53%, 47%)',
  [TokenNames.colorLinkActive]: 'hsl(206deg, 53%, 52%)',
  [TokenNames.colorLinkHover]: 'hsl(206deg, 53%, 52%)',
  [TokenNames.colorLinkVisited]: 'hsl(206deg, 53%, 47%)',
  [TokenNames.colorMath]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorMathActive]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorMathHover]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorBgNote]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgNoteActive]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgNoteHover]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgInfo]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgInfoActive]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgInfoHover]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgSuccess]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgSuccessActive]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgSuccessHover]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgWarning]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgWarningActive]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgWarningHover]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgError]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgErrorActive]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgErrorHover]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: 'none',
  [TokenNames.colorBgBlockquoteActive]: 'none',
  [TokenNames.colorBgBlockquoteHover]: 'none',
  [TokenNames.colorBgCode]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBgCodeActive]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBgCodeHover]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBgCodeHighlight]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgCodeHighlightActive]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgCodeHighlightHover]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgInlineCode]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeActive]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeHover]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgTableHead]: 'hsl(0deg, 0%, 94%)',
  [TokenNames.colorBgTableHeadActive]: 'hsl(0deg, 0%, 94%)',
  [TokenNames.colorBgTableHeadHover]: 'hsl(0deg, 0%, 94%)',
  [TokenNames.colorBgTableOddRow]: 'hsl(0deg, 0%, 100%)',
  [TokenNames.colorBgTableOddRowActive]: 'hsl(0deg, 0%, 100%)',
  [TokenNames.colorBgTableOddRowHover]: 'hsl(0deg, 0%, 100%)',
  [TokenNames.colorBgTableEvenRow]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBgTableEvenRowActive]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBgTableEvenRowHover]: 'hsl(0deg, 0%, 96%)',
  [TokenNames.colorBorderNote]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderNoteActive]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderNoteHover]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderInfo]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderInfoActive]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderInfoHover]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderSuccess]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderSuccessActive]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderSuccessHover]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderWarning]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderWarningActive]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderWarningHover]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderError]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderErrorActive]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderErrorHover]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderBlockquote]: 'hsl(210deg, 13%, 85%)',
  [TokenNames.colorBorderBlockquoteActive]: 'hsl(210deg, 13%, 85%)',
  [TokenNames.colorBorderBlockquoteHover]: 'hsl(210deg, 13%, 85%)',
  [TokenNames.colorBorderCode]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeActive]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeHover]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLineno]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLinenoActive]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLinenoHover]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderHeading]: 'hsl(0deg, 0%, 80%)',
  [TokenNames.colorBorderHeadingActive]: 'hsl(0deg, 0%, 80%)',
  [TokenNames.colorBorderHeadingHover]: 'hsl(0deg, 0%, 80%)',
  [TokenNames.colorBorderImage]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderImageActive]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderImageHover]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderTable]: 'hsl(220deg, 7%, 90%)',
  [TokenNames.colorBorderTableActive]: 'hsl(220deg, 7%, 90%)',
  [TokenNames.colorBorderTableHover]: 'hsl(220deg, 7%, 90%)',
  [TokenNames.colorBorderThematicBreak]: 'hsl(200deg, 15%, 90%)',
  [TokenNames.colorBorderThematicBreakActive]: 'hsl(200deg, 15%, 90%)',
  [TokenNames.colorBorderThematicBreakHover]: 'hsl(200deg, 15%, 90%)',
}
