import { TokenNames } from '../constant/TokenNames'
import type { IThemeSchema } from '../types'

export const lightSchema: IThemeSchema = {
  [TokenNames.colorNote]: '#474748',
  [TokenNames.colorNoteActive]: '#474748',
  [TokenNames.colorNoteHover]: '#474748',
  [TokenNames.colorInfo]: '#474748',
  [TokenNames.colorInfoActive]: '#474748',
  [TokenNames.colorInfoHover]: '#474748',
  [TokenNames.colorSuccess]: '#474748',
  [TokenNames.colorSuccessActive]: '#474748',
  [TokenNames.colorSuccessHover]: '#474748',
  [TokenNames.colorWarning]: '#474748',
  [TokenNames.colorWarningActive]: '#474748',
  [TokenNames.colorWarningHover]: '#474748',
  [TokenNames.colorError]: '#474748',
  [TokenNames.colorErrorActive]: '#474748',
  [TokenNames.colorErrorHover]: '#474748',
  [TokenNames.colorBody]: '#999999',
  [TokenNames.colorBodyActive]: '#999999',
  [TokenNames.colorBodyHover]: '#999999',
  [TokenNames.colorCodeCaret]: '#ED6C60',
  [TokenNames.colorCodeCaretActive]: '#ED6C60',
  [TokenNames.colorCodeCaretHover]: '#ED6C60',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorCodeTitleActive]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorCodeTitleHover]: 'hsla(0deg, 0%, 30%, 0.8)',
  [TokenNames.colorDelete]: '#ACB2B9',
  [TokenNames.colorDeleteActive]: '#ACB2B9',
  [TokenNames.colorDeleteHover]: '#ACB2B9',
  [TokenNames.colorHeading]: '#404040',
  [TokenNames.colorHeadingActive]: '#404040',
  [TokenNames.colorHeadingHover]: '#404040',
  [TokenNames.colorImageTitle]: '#808080',
  [TokenNames.colorImageTitleActive]: '#808080',
  [TokenNames.colorImageTitleHover]: '#808080',
  [TokenNames.colorInlineCode]: '#D81848',
  [TokenNames.colorInlineCodeActive]: '#D81848',
  [TokenNames.colorInlineCodeHover]: '#D81848',
  [TokenNames.colorLink]: '#4682B4',
  [TokenNames.colorLinkActive]: '#5C9FD6',
  [TokenNames.colorLinkHover]: '#5C9FD6',
  [TokenNames.colorLinkVisit]: '#4682B4',
  [TokenNames.colorMath]: '#003399',
  [TokenNames.colorMathActive]: '#003399',
  [TokenNames.colorMathHover]: '#003399',
  [TokenNames.colorBgNote]: '#FDFDFE',
  [TokenNames.colorBgNoteActive]: '#FDFDFE',
  [TokenNames.colorBgNoteHover]: '#FDFDFE',
  [TokenNames.colorBgInfo]: '#EEF9FD',
  [TokenNames.colorBgInfoActive]: '#EEF9FD',
  [TokenNames.colorBgInfoHover]: '#EEF9FD',
  [TokenNames.colorBgSuccess]: '#E6F6E6',
  [TokenNames.colorBgSuccessActive]: '#E6F6E6',
  [TokenNames.colorBgSuccessHover]: '#E6F6E6',
  [TokenNames.colorBgWarning]: '#FFF8E6',
  [TokenNames.colorBgWarningActive]: '#FFF8E6',
  [TokenNames.colorBgWarningHover]: '#FFF8E6',
  [TokenNames.colorBgError]: '#FFEBEC',
  [TokenNames.colorBgErrorActive]: '#FFEBEC',
  [TokenNames.colorBgErrorHover]: '#FFEBEC',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: 'none',
  [TokenNames.colorBgBlockquoteActive]: 'none',
  [TokenNames.colorBgBlockquoteHover]: 'none',
  [TokenNames.colorBgCode]: '#F5F5F5',
  [TokenNames.colorBgCodeActive]: '#F5F5F5',
  [TokenNames.colorBgCodeHover]: '#F5F5F5',
  [TokenNames.colorBgCodeHighlight]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgCodeHighlightActive]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgCodeHighlightHover]: 'hsla(30deg, 90%, 50%, 0.3)',
  [TokenNames.colorBgInlineCode]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeActive]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgInlineCodeHover]: 'hsla(210deg, 15%, 60%, 0.15)',
  [TokenNames.colorBgTableHead]: '#EFF0F0',
  [TokenNames.colorBgTableHeadActive]: '#EFF0F0',
  [TokenNames.colorBgTableHeadHover]: '#EFF0F0',
  [TokenNames.colorBgTableOddRow]: '#FFFFFF',
  [TokenNames.colorBgTableOddRowActive]: '#FFFFFF',
  [TokenNames.colorBgTableOddRowHover]: '#FFFFFF',
  [TokenNames.colorBgTableEvenRow]: '#F6F8FA',
  [TokenNames.colorBgTableEvenRowActive]: '#F6F8FA',
  [TokenNames.colorBgTableEvenRowHover]: '#F6F8FA',
  [TokenNames.colorBorderNote]: '#D4D5D8',
  [TokenNames.colorBorderNoteActive]: '#D4D5D8',
  [TokenNames.colorBorderNoteHover]: '#D4D5D8',
  [TokenNames.colorBorderInfo]: '#4CB3D4',
  [TokenNames.colorBorderInfoActive]: '#4CB3D4',
  [TokenNames.colorBorderInfoHover]: '#4CB3D4',
  [TokenNames.colorBorderSuccess]: '#009400',
  [TokenNames.colorBorderSuccessActive]: '#009400',
  [TokenNames.colorBorderSuccessHover]: '#009400',
  [TokenNames.colorBorderWarning]: '#E6A700',
  [TokenNames.colorBorderWarningActive]: '#E6A700',
  [TokenNames.colorBorderWarningHover]: '#E6A700',
  [TokenNames.colorBorderError]: '#E13238',
  [TokenNames.colorBorderErrorActive]: '#E13238',
  [TokenNames.colorBorderErrorHover]: '#E13238',
  [TokenNames.colorBorderBlockquote]: '#DADDE1',
  [TokenNames.colorBorderBlockquoteActive]: '#DADDE1',
  [TokenNames.colorBorderBlockquoteHover]: '#DADDE1',
  [TokenNames.colorBorderCode]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeActive]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeHover]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLineno]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLinenoActive]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderCodeLinenoHover]: 'hsla(0deg, 0%, 80%, 0.8)',
  [TokenNames.colorBorderHeading]: 'hsla(0deg, 0%, 80%, 1)',
  [TokenNames.colorBorderHeadingActive]: 'hsla(0deg, 0%, 80%, 1)',
  [TokenNames.colorBorderHeadingHover]: 'hsla(0deg, 0%, 80%, 1)',
  [TokenNames.colorBorderImage]: '#7A6390',
  [TokenNames.colorBorderImageActive]: '#7A6390',
  [TokenNames.colorBorderImageHover]: '#7A6390',
  [TokenNames.colorBorderTable]: '#DFE2E5',
  [TokenNames.colorBorderTableActive]: '#DFE2E5',
  [TokenNames.colorBorderTableHover]: '#DFE2E5',
  [TokenNames.colorBorderThematicBreak]: '#E1E4E8',
  [TokenNames.colorBorderThematicBreakActive]: '#E1E4E8',
  [TokenNames.colorBorderThematicBreakHover]: '#E1E4E8',
  [TokenNames.fontFamilyCode]: `Consolas, 'Source Code Pro', 'Roboto Mono', monospace, sans-serif`,
  [TokenNames.fontFamilyHeading]: `'Comic Sans MS', 'lucida grande', 'lucida sans unicode', lucida, 'Hiragino Sans GB', 'Helvetica Neue', 'Microsoft Yahei', 'WenQuanYi Micro Hei', sans-serif`,
  [TokenNames.fontFamilyBody]: `'PingFang SC', system-ui, -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica, sans-serif`,
  [TokenNames.fontSizeCode]: '14px',
  [TokenNames.fontSizeBody]: '16px',
  [TokenNames.marginBlockNode]: '0 0 1.25em 0',
  [TokenNames.marginEmphasis]: '0 6px 0 2px',
  [TokenNames.marginThematicBreak]: '1.5em 0',
}
