export enum CommonTokenNames {
  // Font families
  fontFamilyCode = '--yozora_fontFamilyCode',
  fontFamilyHeading = '--yozora_fontFamilyHeading',
  fontFamilyBody = '--yozora_fontFamilyBody',

  // Font sizes
  fontSizeCode = '--yozora_fontSizeCode',
  fontSizeBody = '--yozora_fontSizeBody',

  // Line height
  lineHeightCode = '--yozora_lineHeightCode',

  // Margin
  marginBlockNode = '--yozora_marginBlockNode',
  marginEmphasis = '--yozora_marginEmphasis',
  marginThematicBreak = '--yozora_marginThematicBreak',
}

export enum TokenNames {
  // Foreground colors
  colorNote = '--yozora_colorNote',
  colorNoteActive = '--yozora_colorNoteActive',
  colorNoteHover = '--yozora_colorNoteHover',
  colorInfo = '--yozora_colorInfo',
  colorInfoActive = '--yozora_colorInfoActive',
  colorInfoHover = '--yozora_colorInfoHover',
  colorSuccess = '--yozora_colorSuccess',
  colorSuccessActive = '--yozora_colorSuccessActive',
  colorSuccessHover = '--yozora_colorSuccessHover',
  colorWarning = '--yozora_colorWarning',
  colorWarningActive = '--yozora_colorWarningActive',
  colorWarningHover = '--yozora_colorWarningHover',
  colorError = '--yozora_colorError',
  colorErrorActive = '--yozora_colorErrorActive',
  colorErrorHover = '--yozora_colorErrorHover',
  colorBody = '--yozora_colorBody',
  colorBodyActive = '--yozora_colorBodyActive',
  colorBodyHover = '--yozora_colorBodyHover',
  colorCodeCaret = '--yozora_colorCodeCaret',
  colorCodeCaretActive = '--yozora_colorCodeCaretActive',
  colorCodeCaretHover = '--yozora_colorCodeCaretHover',
  colorCodeSelection = '--yozora_colorCodeSelection',
  colorCodeSelectionActive = '--yozora_colorCodeSelectionActive',
  colorCodeSelectionHover = '--yozora_colorCodeSelectionHover',
  colorCodeTitle = '--yozora_colorCodeTitle',
  colorCodeTitleActive = '--yozora_colorCodeTitleActive',
  colorCodeTitleHover = '--yozora_colorCodeTitleHover',
  colorDelete = '--yozora_colorDelete',
  colorDeleteActive = '--yozora_colorDeleteActive',
  colorDeleteHover = '--yozora_colorDeleteHover',
  colorHeading = '--yozora_colorHeading',
  colorHeadingActive = '--yozora_colorHeadingActive',
  colorHeadingHover = '--yozora_colorHeadingHover',
  colorImageTitle = '--yozora_colorImageTitle',
  colorImageTitleActive = '--yozora_colorImageTitleActive',
  colorImageTitleHover = '--yozora_colorImageTitleHover',
  colorInlineCode = '--yozora_colorInlineCode',
  colorInlineCodeActive = '--yozora_colorInlineCodeActive',
  colorInlineCodeHover = '--yozora_colorInlineCodeHover',
  colorLink = '--yozora_colorLink',
  colorLinkActive = '--yozora_colorLinkActive',
  colorLinkHover = '--yozora_colorLinkHover',
  colorLinkVisited = '--yozora_colorLinkVisited',
  colorMath = '--yozora_colorMath',
  colorMathActive = '--yozora_colorMathActive',
  colorMathHover = '--yozora_colorMathHover',

  // Background colors
  colorBgNote = '--yozora_colorBgNote',
  colorBgNoteActive = '--yozora_colorBgNoteActive',
  colorBgNoteHover = '--yozora_colorBgNoteHover',
  colorBgInfo = '--yozora_colorBgInfo',
  colorBgInfoActive = '--yozora_colorBgInfoActive',
  colorBgInfoHover = '--yozora_colorBgInfoHover',
  colorBgSuccess = '--yozora_colorBgSuccess',
  colorBgSuccessActive = '--yozora_colorBgSuccessActive',
  colorBgSuccessHover = '--yozora_colorBgSuccessHover',
  colorBgWarning = '--yozora_colorBgWarning',
  colorBgWarningActive = '--yozora_colorBgWarningActive',
  colorBgWarningHover = '--yozora_colorBgWarningHover',
  colorBgError = '--yozora_colorBgError',
  colorBgErrorActive = '--yozora_colorBgErrorActive',
  colorBgErrorHover = '--yozora_colorBgErrorHover',
  colorBgBody = '--yozora_colorBgBody',
  colorBgBodyActive = '--yozora_colorBgBodyActive',
  colorBgBodyHover = '--yozora_colorBgBodyHover',
  colorBgBlockquote = '--yozora_colorBgBlockquote',
  colorBgBlockquoteActive = '--yozora_colorBgBlockquoteActive',
  colorBgBlockquoteHover = '--yozora_colorBgBlockquoteHover',
  colorBgCode = '--yozora_colorBgCode',
  colorBgCodeActive = '--yozora_colorBgCodeActive',
  colorBgCodeHover = '--yozora_colorBgCodeHover',
  colorBgCodeHighlight = '--yozora_colorBgCodeHighlight',
  colorBgCodeHighlightActive = '--yozora_colorBgCodeHighlightActive',
  colorBgCodeHighlightHover = '--yozora_colorBgCodeHighlightHover',
  colorBgInlineCode = '--yozora_colorBgInlineCode',
  colorBgInlineCodeActive = '--yozora_colorBgInlineCodeActive',
  colorBgInlineCodeHover = '--yozora_colorBgInlineCodeHover',
  colorBgTableHead = '--yozora_colorBgTableHead',
  colorBgTableHeadActive = '--yozora_colorBgTableHeadActive',
  colorBgTableHeadHover = '--yozora_colorBgTableHeadHover',
  colorBgTableOddRow = '--yozora_colorBgTableOddRow',
  colorBgTableOddRowActive = '--yozora_colorBgTableOddRowActive',
  colorBgTableOddRowHover = '--yozora_colorBgTableOddRowHover',
  colorBgTableEvenRow = '--yozora_colorBgTableEvenRow',
  colorBgTableEvenRowActive = '--yozora_colorBgTableEvenRowActive',
  colorBgTableEvenRowHover = '--yozora_colorBgTableEvenRowHover',

  // Border colors
  colorBorderNote = '--yozora_colorBorderNote',
  colorBorderNoteActive = '--yozora_colorBorderNoteActive',
  colorBorderNoteHover = '--yozora_colorBorderNoteHover',
  colorBorderInfo = '--yozora_colorBorderInfo',
  colorBorderInfoActive = '--yozora_colorBorderInfoActive',
  colorBorderInfoHover = '--yozora_colorBorderInfoHover',
  colorBorderSuccess = '--yozora_colorBorderSuccess',
  colorBorderSuccessActive = '--yozora_colorBorderSuccessActive',
  colorBorderSuccessHover = '--yozora_colorBorderSuccessHover',
  colorBorderWarning = '--yozora_colorBorderWarning',
  colorBorderWarningActive = '--yozora_colorBorderWarningActive',
  colorBorderWarningHover = '--yozora_colorBorderWarningHover',
  colorBorderError = '--yozora_colorBorderError',
  colorBorderErrorActive = '--yozora_colorBorderErrorActive',
  colorBorderErrorHover = '--yozora_colorBorderErrorHover',
  colorBorderBlockquote = '--yozora_colorBorderBlockquote',
  colorBorderBlockquoteActive = '--yozora_colorBorderBlockquoteActive',
  colorBorderBlockquoteHover = '--yozora_colorBorderBlockquoteHover',
  colorBorderCode = '--yozora_colorBorderCode',
  colorBorderCodeActive = '--yozora_colorBorderCodeActive',
  colorBorderCodeHover = '--yozora_colorBorderCodeHover',
  colorBorderCodeLineno = '--yozora_colorBorderCodeLineno',
  colorBorderCodeLinenoActive = '--yozora_colorBorderCodeLinenoActive',
  colorBorderCodeLinenoHover = '--yozora_colorBorderCodeLinenoHover',
  colorBorderHeading = '--yozora_colorBorderHeading',
  colorBorderHeadingActive = '--yozora_colorBorderHeadingActive',
  colorBorderHeadingHover = '--yozora_colorBorderHeadingHover',
  colorBorderImage = '--yozora_colorBorderImage',
  colorBorderImageActive = '--yozora_colorBorderImageActive',
  colorBorderImageHover = '--yozora_colorBorderImageHover',
  colorBorderTable = '--yozora_colorBorderTable',
  colorBorderTableActive = '--yozora_colorBorderTableActive',
  colorBorderTableHover = '--yozora_colorBorderTableHover',
  colorBorderThematicBreak = '--yozora_colorBorderThematicBreak',
  colorBorderThematicBreakActive = '--yozora_colorBorderThematicBreakActive',
  colorBorderThematicBreakHover = '--yozora_colorBorderThematicBreakHover',
}

type IKey = keyof typeof CommonTokenNames | keyof typeof TokenNames
type ICssVariable = `var(--${string})`

export const tokens: Record<IKey, ICssVariable> = Object.fromEntries(
  [...Object.entries(CommonTokenNames), ...Object.entries(TokenNames)]
    .filter(([key]) => Number.isNaN(Number(key)))
    .map(([key, val]) => [key, `var(${val})`] as [IKey, ICssVariable]),
) as Record<IKey, ICssVariable>
