import './prismjs/prism-dot'
import './prismjs/prism-visual-basic'
import './style.styl'

export * from './component'
export * from './content'
export * from './types'
export { vscDarkTheme } from './theme/vsc-dark'
export { vscLightTheme } from './theme/vsc-light'
export { CodeHighlighter as default } from './component'
