import { TokenNames } from '../../constant/token'

export const darkenSchema: Record<TokenNames, string> = {
  [TokenNames.colorNote]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorNoteActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorNoteHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfo]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfoActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorInfoHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccess]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccessActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorSuccessHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarning]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarningActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorWarningHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorError]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorErrorActive]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorErrorHover]: 'hsl(0deg, 0%, 99%)',
  [TokenNames.colorBody]: '#cbd5e1',
  [TokenNames.colorBodyActive]: '#cbd5e1',
  [TokenNames.colorBodyHover]: '#cbd5e1',
  [TokenNames.colorCodeCaret]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeCaretActive]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeCaretHover]: 'hsl(240deg, 3%, 67%)',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: '#94a3b8',
  [TokenNames.colorCodeTitleActive]: '#94a3b8',
  [TokenNames.colorCodeTitleHover]: '#94a3b8',
  [TokenNames.colorDelete]: '#94a3b8',
  [TokenNames.colorDeleteActive]: '#94a3b8',
  [TokenNames.colorDeleteHover]: '#94a3b8',
  [TokenNames.colorHeading]: '#f1f5f9',
  [TokenNames.colorHeadingActive]: '#f1f5f9',
  [TokenNames.colorHeadingHover]: '#f1f5f9',
  [TokenNames.colorImageTitle]: '#94a3b8',
  [TokenNames.colorImageTitleActive]: '#94a3b8',
  [TokenNames.colorImageTitleHover]: '#94a3b8',
  [TokenNames.colorInlineCode]: '#e2e8f0',
  [TokenNames.colorInlineCodeActive]: '#e2e8f0',
  [TokenNames.colorInlineCodeHover]: '#e2e8f0',
  [TokenNames.colorLink]: '#93c5fd',
  [TokenNames.colorLinkActive]: '#bfdbfe',
  [TokenNames.colorLinkHover]: '#bfdbfe',
  [TokenNames.colorLinkVisited]: '#93c5fd',
  [TokenNames.colorMath]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorMathActive]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorMathHover]: 'hsl(0deg, 0%, 75%)',
  [TokenNames.colorBgNote]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgNoteActive]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgNoteHover]: 'hsl(210deg, 10%, 28%)',
  [TokenNames.colorBgInfo]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgInfoActive]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgInfoHover]: 'hsl(198deg, 45%, 11%)',
  [TokenNames.colorBgSuccess]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgSuccessActive]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgSuccessHover]: 'hsl(120deg, 100%, 15%)',
  [TokenNames.colorBgWarning]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgWarningActive]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgWarningHover]: 'hsl(45deg, 100%, 20%)',
  [TokenNames.colorBgError]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgErrorActive]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgErrorHover]: 'hsl(0deg, 75%, 25%)',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: '#202b3a',
  [TokenNames.colorBgBlockquoteActive]: '#202b3a',
  [TokenNames.colorBgBlockquoteHover]: '#202b3a',
  [TokenNames.colorBgCode]: '#151e2a',
  [TokenNames.colorBgCodeActive]: '#151e2a',
  [TokenNames.colorBgCodeHover]: '#151e2a',
  [TokenNames.colorBgCodeHighlight]: 'rgba(96, 165, 250, 0.12)',
  [TokenNames.colorBgCodeHighlightActive]: 'rgba(96, 165, 250, 0.12)',
  [TokenNames.colorBgCodeHighlightHover]: 'rgba(96, 165, 250, 0.12)',
  [TokenNames.colorBgInlineCode]: '#293548',
  [TokenNames.colorBgInlineCodeActive]: '#293548',
  [TokenNames.colorBgInlineCodeHover]: '#293548',
  [TokenNames.colorBgTableHead]: '#202b3a',
  [TokenNames.colorBgTableHeadActive]: '#202b3a',
  [TokenNames.colorBgTableHeadHover]: '#202b3a',
  [TokenNames.colorBgTableOddRow]: '#18212c',
  [TokenNames.colorBgTableOddRowActive]: '#18212c',
  [TokenNames.colorBgTableOddRowHover]: '#18212c',
  [TokenNames.colorBgTableEvenRow]: '#1b2633',
  [TokenNames.colorBgTableEvenRowActive]: '#1b2633',
  [TokenNames.colorBgTableEvenRowHover]: '#1b2633',
  [TokenNames.colorBorderNote]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderNoteActive]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderNoteHover]: 'hsl(210deg, 2%, 83%)',
  [TokenNames.colorBorderInfo]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderInfoActive]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderInfoHover]: 'hsl(190deg, 49%, 48%)',
  [TokenNames.colorBorderSuccess]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderSuccessActive]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderSuccessHover]: 'hsl(120deg, 100%, 30%)',
  [TokenNames.colorBorderWarning]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderWarningActive]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderWarningHover]: 'hsl(43deg, 90%, 45%)',
  [TokenNames.colorBorderError]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderErrorActive]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderErrorHover]: 'hsl(358deg, 82%, 50%)',
  [TokenNames.colorBorderBlockquote]: '#475569',
  [TokenNames.colorBorderBlockquoteActive]: '#475569',
  [TokenNames.colorBorderBlockquoteHover]: '#475569',
  [TokenNames.colorBorderCode]: '#334155',
  [TokenNames.colorBorderCodeActive]: '#334155',
  [TokenNames.colorBorderCodeHover]: '#334155',
  [TokenNames.colorBorderCodeLineno]: '#334155',
  [TokenNames.colorBorderCodeLinenoActive]: '#334155',
  [TokenNames.colorBorderCodeLinenoHover]: '#334155',
  [TokenNames.colorBorderHeading]: '#334155',
  [TokenNames.colorBorderHeadingActive]: '#334155',
  [TokenNames.colorBorderHeadingHover]: '#334155',
  [TokenNames.colorBorderImage]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderImageActive]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderImageHover]: 'hsl(290deg, 15%, 49%)',
  [TokenNames.colorBorderTable]: '#334155',
  [TokenNames.colorBorderTableActive]: '#334155',
  [TokenNames.colorBorderTableHover]: '#334155',
  [TokenNames.colorBorderThematicBreak]: '#334155',
  [TokenNames.colorBorderThematicBreakActive]: '#334155',
  [TokenNames.colorBorderThematicBreakHover]: '#334155',
}
