import { TokenNames } from '../../constant/token'

export const lightSchema: Record<TokenNames, string> = {
  [TokenNames.colorNote]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorNoteActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorNoteHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfo]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfoActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorInfoHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccess]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccessActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorSuccessHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarning]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarningActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorWarningHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorError]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorErrorActive]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorErrorHover]: 'hsl(0deg, 0%, 28%)',
  [TokenNames.colorBody]: '#374151',
  [TokenNames.colorBodyActive]: '#374151',
  [TokenNames.colorBodyHover]: '#374151',
  [TokenNames.colorCodeCaret]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeCaretActive]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeCaretHover]: 'hsl(355deg, 68%, 53%)',
  [TokenNames.colorCodeSelection]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionActive]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeSelectionHover]: 'hsla(200deg, 30%, 70%, 0.3)',
  [TokenNames.colorCodeTitle]: '#64748b',
  [TokenNames.colorCodeTitleActive]: '#64748b',
  [TokenNames.colorCodeTitleHover]: '#64748b',
  [TokenNames.colorDelete]: '#64748b',
  [TokenNames.colorDeleteActive]: '#64748b',
  [TokenNames.colorDeleteHover]: '#64748b',
  [TokenNames.colorHeading]: '#111827',
  [TokenNames.colorHeadingActive]: '#111827',
  [TokenNames.colorHeadingHover]: '#111827',
  [TokenNames.colorImageTitle]: '#64748b',
  [TokenNames.colorImageTitleActive]: '#64748b',
  [TokenNames.colorImageTitleHover]: '#64748b',
  [TokenNames.colorInlineCode]: '#334155',
  [TokenNames.colorInlineCodeActive]: '#334155',
  [TokenNames.colorInlineCodeHover]: '#334155',
  [TokenNames.colorLink]: '#2563eb',
  [TokenNames.colorLinkActive]: '#1d4ed8',
  [TokenNames.colorLinkHover]: '#1d4ed8',
  [TokenNames.colorLinkVisited]: '#2563eb',
  [TokenNames.colorMath]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorMathActive]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorMathHover]: 'hsl(220deg, 100%, 20%)',
  [TokenNames.colorBgNote]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgNoteActive]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgNoteHover]: 'hsl(240deg, 3%, 99%)',
  [TokenNames.colorBgInfo]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgInfoActive]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgInfoHover]: 'hsl(197deg, 79%, 98%)',
  [TokenNames.colorBgSuccess]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgSuccessActive]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgSuccessHover]: 'hsl(125deg, 50%, 92%)',
  [TokenNames.colorBgWarning]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgWarningActive]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgWarningHover]: 'hsl(39deg, 100%, 95%)',
  [TokenNames.colorBgError]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgErrorActive]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgErrorHover]: 'hsl(0deg, 87%, 94%)',
  [TokenNames.colorBgBody]: 'none',
  [TokenNames.colorBgBodyActive]: 'none',
  [TokenNames.colorBgBodyHover]: 'none',
  [TokenNames.colorBgBlockquote]: '#f8fafc',
  [TokenNames.colorBgBlockquoteActive]: '#f8fafc',
  [TokenNames.colorBgBlockquoteHover]: '#f8fafc',
  [TokenNames.colorBgCode]: '#f8fafc',
  [TokenNames.colorBgCodeActive]: '#f8fafc',
  [TokenNames.colorBgCodeHover]: '#f8fafc',
  [TokenNames.colorBgCodeHighlight]: 'rgba(59, 130, 246, 0.09)',
  [TokenNames.colorBgCodeHighlightActive]: 'rgba(59, 130, 246, 0.09)',
  [TokenNames.colorBgCodeHighlightHover]: 'rgba(59, 130, 246, 0.09)',
  [TokenNames.colorBgInlineCode]: '#f1f5f9',
  [TokenNames.colorBgInlineCodeActive]: '#f1f5f9',
  [TokenNames.colorBgInlineCodeHover]: '#f1f5f9',
  [TokenNames.colorBgTableHead]: '#f8fafc',
  [TokenNames.colorBgTableHeadActive]: '#f8fafc',
  [TokenNames.colorBgTableHeadHover]: '#f8fafc',
  [TokenNames.colorBgTableOddRow]: '#ffffff',
  [TokenNames.colorBgTableOddRowActive]: '#ffffff',
  [TokenNames.colorBgTableOddRowHover]: '#ffffff',
  [TokenNames.colorBgTableEvenRow]: '#fafbfc',
  [TokenNames.colorBgTableEvenRowActive]: '#fafbfc',
  [TokenNames.colorBgTableEvenRowHover]: '#fafbfc',
  [TokenNames.colorBorderNote]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderNoteActive]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderNoteHover]: 'hsl(208deg, 9%, 85%)',
  [TokenNames.colorBorderInfo]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderInfoActive]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderInfoHover]: 'hsl(190deg, 50%, 52%)',
  [TokenNames.colorBorderSuccess]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderSuccessActive]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderSuccessHover]: 'hsl(120deg, 100%, 25%)',
  [TokenNames.colorBorderWarning]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderWarningActive]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderWarningHover]: 'hsl(39deg, 100%, 55%)',
  [TokenNames.colorBorderError]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderErrorActive]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderErrorHover]: 'hsl(355deg, 72%, 54%)',
  [TokenNames.colorBorderBlockquote]: '#cbd5e1',
  [TokenNames.colorBorderBlockquoteActive]: '#cbd5e1',
  [TokenNames.colorBorderBlockquoteHover]: '#cbd5e1',
  [TokenNames.colorBorderCode]: '#e2e8f0',
  [TokenNames.colorBorderCodeActive]: '#e2e8f0',
  [TokenNames.colorBorderCodeHover]: '#e2e8f0',
  [TokenNames.colorBorderCodeLineno]: '#e2e8f0',
  [TokenNames.colorBorderCodeLinenoActive]: '#e2e8f0',
  [TokenNames.colorBorderCodeLinenoHover]: '#e2e8f0',
  [TokenNames.colorBorderHeading]: '#e5e7eb',
  [TokenNames.colorBorderHeadingActive]: '#e5e7eb',
  [TokenNames.colorBorderHeadingHover]: '#e5e7eb',
  [TokenNames.colorBorderImage]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderImageActive]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderImageHover]: 'hsl(277deg, 19%, 47%)',
  [TokenNames.colorBorderTable]: '#e2e8f0',
  [TokenNames.colorBorderTableActive]: '#e2e8f0',
  [TokenNames.colorBorderTableHover]: '#e2e8f0',
  [TokenNames.colorBorderThematicBreak]: '#e5e7eb',
  [TokenNames.colorBorderThematicBreakActive]: '#e5e7eb',
  [TokenNames.colorBorderThematicBreakHover]: '#e5e7eb',
}
